### ISSUE TITLE
Please show the results with OPCache On

### ISSUE THREAD

**Issue by joanhey** [myaaghubi/PHP-Frameworks-Bench#11]
Nobody use an app or framework in PHP without OPCache, and less in production.

Even the shared hostings use it, and the Kenjis bench data also.
And it's a bad image for PHP, because a lot of people think that is slow, and without OPCache the numbers are not reallistic.

**Comment by myaaghubi** [comment]
The config of my old machine is not popular so the measured numbers aren't really important, the ratio between numbers makes sense and it's almost the same as the `opcache on`. There are other ways too to speed up a php project and `opcache` is a caching system by the way so with `opcache off` numbers are more realistic however results with `opcache on` listed in the video in the `README.md`
