### ISSUE TITLE
Syler has been archived

### ISSUE THREAD

**Issue by joanhey** [myaaghubi/PHP-Frameworks-Bench#30]
After seen deprecated errors, I went to the repo for a new version and found that.
https://github.com/leocavalcante/siler

![image](https://github.com/myaaghubi/PHP-Frameworks-Bench/assets/249085/f67d7bd1-b320-4b6a-9a17-afcfb9ad9f55)

Errors:
![image](https://github.com/myaaghubi/PHP-Frameworks-Bench/assets/249085/42946a85-7c46-45f5-9aba-de0f048c9b6d)

**Comment by myaaghubi** [comment]
Yeh, it was archived from the very beginning of this repo
I put it because it was one of the faster libs to have a comparison with slower but now we can just remove it a0c506220cc71cc81bc2941363918a94d105fb71, fb88615ba7503c99f3cdfa02131c2474d961a81d
