### ISSUE TITLE
The `output_data.php` don't work with PHP-FPM in some frameworks

### ISSUE THREAD

**Issue by joanhey** [myaaghubi/PHP-Frameworks-Bench#39]
[PHP-FPM](https://www.php.net/manual/en/install.fpm.php) has become the de-facto process manager for PHP, providing more flexibility than the venerable PHP module for Apache.

All frameworks that use the Symfony kernel, output no data after the _Hello World!_.

> Internally, the HttpKernel makes use of the [fastcgi_finish_request](https://secure.php.net/manual/en/function.fastcgi-finish-request.php) PHP function.

https://symfony.com/doc/current/components/http_kernel.html#component-http-kernel-kernel-terminate

Frameworks that fail:

- Symfony 5.4 and 6.3
- Laravel 10
- Lumen 10
- Silex

![image](https://github.com/myaaghubi/PHP-Frameworks-Bench/assets/249085/5046bc07-f91a-4c20-bd57-a2bda3d74ef0)

We need to search a solution.

**Comment by myaaghubi** [comment]
Same issue with `nginx`, the problem is not about `output_data.php` the mechanism is to measure via output_data.php at the end of the script but requests get finished before reaching the end via `fastcgi_finish_request` or `litespeed_finish_request`

**Comment by joanhey** [comment]
We can require the `output_data.php` in the same controller method, for that frameworks.

```php
class HelloWorldController extends Controller {
    public function index(): void {
        echo 'Hello World!';
        /* *** PHP-Frameworks-Bench *** */
        require $_SERVER['DOCUMENT_ROOT'].'/PHP-Frameworks-Bench/libs/output_data.php';
    }
}

```

**Comment by myaaghubi** [comment]
Some libs use `return ...` instead! accuracy not gonna be accurate too. 
Try to run some benchmarks on nginx you gonna surprised as I did once you may believe the Apache again

**Comment by myaaghubi** [comment]
Some frameworks have `return ...` instead, so let's imagine having something like this to make it work
```php
// a simple controller example for Symfony
class HelloWorldController {
    public function index(): Response {
        function outputData(){
            ob_start();
            require($_SERVER['DOCUMENT_ROOT'].'/PHP-Frameworks-Bench/libs/output_data.php');
            return ob_get_clean();
        }
        return new Response('Hello World!'.outputData());
    }
}
```
It is gonna work but the measurement for memory not gonna be accurate. 
Also the cost of rendering output while/after `Response` and `return` not gonna measured. It may, in case, there be no considerable cost after `Response` however this is benchmarking and we need to consider it
