### ISSUE TITLE
Silex it's deprecated from June 2018

### ISSUE THREAD

**Issue by joanhey** [myaaghubi/PHP-Frameworks-Bench#40]
That's 5 years ago EOL.

![image](https://github.com/myaaghubi/PHP-Frameworks-Bench/assets/249085/f585fa1b-9700-45bd-b5cf-82f5baf4d6d1)

https://github.com/silexphp/Silex

> This repository has been archived by the owner on Jul 4, 2018. It is now read-only.

It's better to have frameworks that are maintained in the benchmark.

**Comment by myaaghubi** [comment]
Yep, this is why I mentioned it with `slim 3` it was archived from the very beginning
However it is functional on php 8.2 with no errors so let's keep it
 
![Screenshot from 2023-07-29 15-56-24](https://github.com/myaaghubi/PHP-Frameworks-Bench/assets/4276074/6a0ee8d5-ac8a-4809-bf01-2f3917a30fd5)
_Originally posted by @myaaghubi in https://github.com/myaaghubi/PHP-Frameworks-Bench/issues/31#issuecomment-1656720510_
